# Generated by Django 5.1.6 on 2025-02-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='user',
            new_name='owner',
        ),
    ]
