[tool.poetry]
name = "sarafan"
version = "0.1.0"
description = ""
authors = ["antonglazunov <tagl91@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
