# Generated by Django 5.1.6 on 2025-02-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/category/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/subcategory/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='shop.category', verbose_name='Категория')),
            ],
        ),
    ]
