# Generated by Django 5.1.6 on 2025-02-08 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('[a-z0-9_-]', "slug должен содержать только символы 'a-z', '0-9', '_ -'")], verbose_name='slug'),
        ),
    ]
