# Generated by Django 5.1.6 on 2025-02-08 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('[a-z0-9_-]', "slug должен содержать только символы 'a-z', '0-9', '_ -'")], verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/subcategory/', verbose_name='Изображение оригинал')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='shop/subcategory/', verbose_name='Изображение 600*600')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='shop/subcategory/', verbose_name='Изображение 200*200')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='Цена')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='Подкатегория')),
            ],
        ),
    ]
