# Generated by Django 5.1.6 on 2025-02-08 21:51

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_name_alter_subcategory_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to_product, verbose_name='Изображение оригинал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='shop/product/', verbose_name='Изображение 600*600'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='shop/product/', verbose_name='Изображение 200*200'),
        ),
    ]
